version: '3.2'

services:

    db:
        container_name: db
        image: mysql:8.0.20
        ports:
            - "3333:3306"
        environment:
            MYSQL_DATABASE: "spring_bank_database"
            MYSQL_PASSWORD: root
    web:
        build: .
        ports:
            - "8080:8080"
        environment:
            SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/spring_bank_database?autoReconnect=true&useSSL=false
        depends_on:
            - db